<a href="https://colab.research.google.com/github/Owaiskhan9654/Testing-Singular-Value-Decomposition-SVD/blob/master/SVD(CORE_IMPLEMENTATION).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [126]:
import numpy as np

In [127]:
x=[[5,5],[-1,7]]

In [128]:
# I have to split the matrix x into U,SIGMA,V.....So By multiplying x transpose  and x I will get 
y=np.matmul(np.transpose(x),x) #  split like this (xT).(x)=(v).(sigma.T).(u.T).(u).(sigma).(vT)

# Here U,V are orthogonal and Orthonormal hence (U.T).U=I   ( where I is a Identity Matrix)

In [129]:
y

array([[26, 18],
       [18, 74]])

In [130]:
(eig_values1, eig_vectors1) = np.linalg.eig(y)

In [55]:
eig_values1

array([20., 80.])

In [56]:
eig_values1[::-1].sort()

In [77]:
eig_values1

array([80., 20.])

In [78]:
sigma1=(np.sqrt(eig_values1))

In [80]:
sigma1=np.diag(sigma1) #Diagonalization because multiplication will not be possible

In [81]:
sigma1

array([[8.94427191, 0.        ],
       [0.        , 4.47213595]])

In [82]:
v1=eig_vectors.T

In [62]:
v1

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [83]:
# Now for calculating U applying same procedure as used for calculating V,   i.e  X.(X.T)
z=np.matmul(x,np.transpose(x))

In [84]:
z

array([[50, 30],
       [30, 50]])

In [85]:
(eig_values2, eig_vectors2) = np.linalg.eig(z)

In [86]:
eig_values2

array([80., 20.])

In [75]:
sigma2=(np.sqrt(eig_values2))

In [76]:
sigma2

array([8.94427191, 4.47213595])

In [66]:
eig_vectors2

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [67]:
u=eig_vectors2

In [68]:
u

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

## **From Predefined Method**

In [113]:
u1,sigma3,v1=np.linalg.svd(x)

In [114]:
sigma3=np.diag(sigma3)

In [121]:
print('U Calculated from Predefined Library linalg.SVD \n')
print(u1,'\n')

print('U Calculated from explicit Method \n')
print(u)

U Calculated from Predefined Library linalg.SVD 

[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]] 

U Calculated from explicit Method 

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [120]:
print('Σ Calculated from Predefined Library linalg.SVD \n')
print(sigma3,'\n')

print('Σ Calculated from explicit Method \n')
print(sigma1)

Σ Calculated from Predefined Library linalg.SVD 

[[8.94427191 0.        ]
 [0.         4.47213595]] 

Σ Calculated from explicit Method 

[[8.94427191 0.        ]
 [0.         4.47213595]]


In [119]:
print('V Calculated from Predefined Library linalg.SVD \n')
print(v1,'\n')

print('V Calculated from explicit Method \n')
print(v)

V Calculated from Predefined Library linalg.SVD 

[[ 0.31622777  0.9486833 ]
 [ 0.9486833  -0.31622777]] 

V Calculated from explicit Method 

[[-0.9486833   0.31622777]
 [-0.31622777 -0.9486833 ]]
