In [ ]:
import numpy as np

In [ ]:
x=[[5,5],[-1,7]]

In [ ]:
# I have to split the matrix x into U,SIGMA,V.....So By multiplying x transpose  and x I will get 
y=np.matmul(np.transpose(x),x) #  split like this (xT).(x)=(v).(sigma.T).(u.T).(u).(sigma).(vT)

# Here U,V are orthogonal and Orthonormal hence (U.T).U=I   ( where I is a Identity Matrix)

In [ ]:
y

array([[26, 18],
       [18, 74]])

In [ ]:
(eig_values, eig_vectors) = np.linalg.eig(y.T)

In [ ]:
eig_values

array([20., 80.])

In [ ]:
eig_values[::-1].sort()

In [ ]:
eig_values=(np.sqrt(eig_values))

In [ ]:
eig_values

array([8.94427191, 4.47213595])

In [ ]:
sigma=np.diag(eig_values) #Diagonalization because multiplication will not be possible

In [ ]:
v=eig_vectors

In [ ]:
sigma

array([[0.1118034, 0.       ],
       [0.       , 0.2236068]])

In [ ]:
sigma=np.linalg.inv(sigma)

In [ ]:
sigma

array([[0.1118034, 0.       ],
       [0.       , 0.2236068]])

In [ ]:
m=np.matmul(x,v)

In [ ]:
u=np.matmul(m,sigma)

In [ ]:
u

array([[-0.35355339, -1.41421356],
       [ 0.35355339, -1.41421356]])

## **From Predefined Method**

In [ ]:
u1,sigma1,v1=np.linalg.svd(x)

In [ ]:
u1

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [ ]:
sigma1 #see here Eigen values are reverse order.... yahi shayad problem h

array([8.94427191, 4.47213595])

In [ ]:
v1

array([[ 0.31622777,  0.9486833 ],
       [ 0.9486833 , -0.31622777]])

In [ ]:
v

array([[-0.9486833 , -0.31622777],
       [ 0.31622777, -0.9486833 ]])

In [ ]:
#v and v1 mei dekho,,,,Thoda sa fark h